### PR TITLE
dotgit: clean up ref file after failed setref

### PR DESCRIPTION
**Pull request by strib**
If `Lock` or `CheckClose()` fails (e.g., we're using a networked storage layer and couldn't connect to the server temporarily to do the lock/unlock), we need to revert the local version of the reference file back to what it was before we started messing with it.  For a newly-created file, we should delete it; for other files, we need to revert the contents.  This is to prevent the caller, which might have restored its connectivity, from trying to sync corrupted contents later.

Issue: KBFS-3703

### CODE REVIEW

**Comment by strib** [comment]
Assigned @taruti for review, but cc @jakob223 @jzila @songgao in case anyone else is interested.

**Comment by taruti** [comment]
I think this is correct but I keep thinking there is a better way to do this. Now the ref is read two times.

setRef calls checkReferenceAndTruncate, which reads the reference (and setRef is the only caller). So it might make sense to e.g. inline the code from there and read the contents only once. Also we can be more intelligent when we need to restore the file (if we have already truncated it).

**Comment by strib** [comment]
@taruti thanks for the pointers, the new version is a little cleaner.  Let me know what you think, thanks!

**Comment by taruti** [comment]
LGTM

**Pull request merged**
